language: node_js
node_js:
- '11'
addons:
  ssh_known_hosts:
  - "$REMOTE_HOST"
  - "$REMOTE_HOST_IP"
after_success:
- chmod +x ".travis/public-patch.js"
- chmod +x ".travis/public-deploy.sh"
- node .travis/public-patch.js
- ".travis/public-deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_bcbda17145e7_key -iv $encrypted_bcbda17145e7_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
