environment:
  nodejs_version: "10"
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
test_script:
  - yarn test

build: off

